"""Generate Markdown verification reports."""

from datetime import datetime
from typing import List, Optional

from ..verify import VerificationResult, VerificationStatus, summarize_results


def generate_markdown_report(
    results: List[VerificationResult],
    title: str = "Citation Verification Report",
    include_valid: bool = False,
    include_details: bool = True,
) -> str:
    """Generate a Markdown report from verification results.

    Args:
        results: List of verification results
        title: Report title
        include_valid: Whether to list valid citations
        include_details: Whether to include detailed metadata

    Returns:
        Markdown-formatted report string
    """
    summary = summarize_results(results)

    lines = []

    # Header
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    # Summary section
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total citations | {summary['total']} |")
    lines.append(f"| Valid | {summary['valid']} |")
    lines.append(f"| Warnings | {summary['warnings']} |")
    lines.append(f"| Invalid | {summary['invalid']} |")
    lines.append(f"| Errors | {summary['errors']} |")
    lines.append(f"| **Error rate** | **{summary['error_rate']:.1f}%** |")
    lines.append("")

    # Issues by type
    if summary['issues_by_type']:
        lines.append("### Issues by Type")
        lines.append("")
        lines.append("| Issue Type | Count |")
        lines.append("|------------|-------|")
        for issue_type, count in sorted(summary['issues_by_type'].items()):
            lines.append(f"| {issue_type.replace('_', ' ').title()} | {count} |")
        lines.append("")

    # Invalid citations section
    if summary['invalid_citations']:
        lines.append("## Invalid Citations")
        lines.append("")
        lines.append("These citations have significant issues that should be fixed.")
        lines.append("")

        for result in summary['invalid_citations']:
            lines.extend(_format_citation_result(result, include_details))

    # Warnings section
    if summary['warning_citations']:
        lines.append("## Warnings")
        lines.append("")
        lines.append("These citations have minor issues that may need attention.")
        lines.append("")

        for result in summary['warning_citations']:
            lines.extend(_format_citation_result(result, include_details))

    # Valid citations (optional)
    if include_valid:
        valid_results = [r for r in results if r.status == VerificationStatus.VALID]
        if valid_results:
            lines.append("## Valid Citations")
            lines.append("")

            for result in valid_results:
                lines.append(f"- `{result.citation.doi}` - OK")

            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Generated by Citation Verification Toolkit*")

    return "\n".join(lines)


def _format_citation_result(
    result: VerificationResult,
    include_details: bool = True
) -> List[str]:
    """Format a single citation result as Markdown.

    Args:
        result: Verification result to format
        include_details: Whether to include detailed metadata

    Returns:
        List of Markdown lines
    """
    lines = []
    citation = result.citation

    # Citation header
    lines.append(f"### DOI: `{citation.doi}`")
    lines.append("")

    # Basic info
    if citation.text:
        lines.append(f"**Citation text**: {citation.text}")
    if citation.file_path:
        lines.append(f"**File**: `{citation.file_path}`")
    if citation.line_number > 0:
        lines.append(f"**Line**: {citation.line_number}")
    lines.append("")

    # Issues
    lines.append("**Issues**:")
    lines.append("")
    for issue in result.issues:
        severity_icon = {
            VerificationStatus.INVALID: "❌",
            VerificationStatus.WARNING: "⚠️",
            VerificationStatus.ERROR: "🔴",
        }.get(issue.severity, "•")

        lines.append(f"- {severity_icon} **{issue.type.value.replace('_', ' ').title()}**: {issue.message}")
        if issue.details:
            lines.append(f"  - {issue.details}")

    lines.append("")

    # CrossRef metadata (if available)
    if include_details and result.crossref_metadata:
        meta = result.crossref_metadata
        lines.append("**Actual paper (from CrossRef)**:")
        lines.append("")
        lines.append(f"- Title: {meta.title}")
        lines.append(f"- Authors: {meta.author_string}")
        lines.append(f"- Year: {meta.year}")
        if meta.journal:
            lines.append(f"- Journal: {meta.journal}")
        lines.append("")

    # Suggested fix
    if result.issues:
        lines.append("**Suggested action**:")
        lines.append("")

        primary_issue = result.issues[0].type

        if primary_issue.value == "doi_not_found":
            lines.append("1. Search for the paper by title and author")
            lines.append("2. Find the correct DOI from the publisher or PubMed")
            lines.append("3. Verify the paper actually exists")
        elif primary_issue.value == "wrong_paper":
            lines.append("1. Find the correct paper's DOI")
            lines.append("2. Verify the new DOI matches the citation")
        elif primary_issue.value == "wrong_author":
            lines.append("1. Update citation text to match actual authors")
            lines.append("2. Or find the correct paper if this is the wrong one")
        elif primary_issue.value == "wrong_year":
            lines.append("1. Update citation year to match DOI metadata")
        elif primary_issue.value == "wrong_prefix":
            lines.append("1. Verify the journal name is correct")
            lines.append("2. Find the correct DOI if journal is wrong")

        lines.append("")

    lines.append("---")
    lines.append("")

    return lines


def save_report(
    results: List[VerificationResult],
    output_path: str,
    **kwargs
) -> None:
    """Generate and save a Markdown report to file.

    Args:
        results: Verification results
        output_path: Path to save the report
        **kwargs: Additional arguments for generate_markdown_report
    """
    report = generate_markdown_report(results, **kwargs)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(report)
